{
	"data": "ENC[AES256_GCM,data:hy0Jir1JSutAtbUDWnJQyJFuST3plMsE04t/4eTpTdlm/vyGUAasxYmg/SjCJRa4fsUKckrRHUIliBNcLY1hdG+zgMmpLpxWXyI9XspXyTNsVjaDdvVHMU23nUUDeXgLm8nUv3Nuwd22EtfgXw9uxG0nQ0RQRapwueC47C1BAwRzQlXJwvkdpzsx0FN/MTukcyipbZAC6FVgWcxbZhrWt8GcHyHtnjaCOpM+fvXb+9A5sDOJPa3sjkN88o5DgmLOZlwtcf56+m0zUKnN4St4Mj7LGbjXyw+kBcst+CujhA2DT9eaKVd53kmoBmzDIj5xlBBhZKh+jOMnrPUcdzjxV2mscOKdN29ip4f68csWkos4JUpFqcJqRmZtYuiieNRO8Vs6fcmDD2TPDk6yFamvrnqlUNPppe7eyjcvL47vWRAb9unC6fsgmCrh9AQUSP2KGg+ZF1ovTI2BojqIoqR2afrHubsiYLXYai887mTbPrqLOKsin/+J0ZZGNiWz7gbgSA7GjmThIciintrLLBL01ZCJW+Nc1BH4crGRUcg3dvr6gx6G2vFHlvZ40A0tKKSBjb//Ojw58sB9QGSCllBut51Fnc1QLxikFnjh0Ct9/NuSN+KNmVgvUveHIFu73DcuSsHOuSwj,iv:MU82ldNgMe0HwKlPlGz9vTj3cg5muGRK7KRFVMPEH34=,tag:7v9iFJoNrNwaYFMzlNMGyg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aVNmVkR3akd2RUJoQmpr\nY2F1RjIzQ2ovTGJFN1cwUzZacHNoZlM3RHhRCm9DL1N0Y3BXdVliak40REVFWnZH\nU1VpeHdCYlU1L2dPWWtGbVRyT0ZNcmsKLS0tIHZEZHdGTXJFT0xrRFQwYUV4UUUw\nVmhqTDNRVjFFcHNuaWNFdjlKdFR5RmsKwlWJkmEoSWer2kT2/ciCTuIcfIOtcm6K\n/amzhsQ2FRNdyBsPkvbrSsZ+FLe/lZXRjvngxxzeCL+mh3WHc36cpA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c"
			}
		],
		"lastmodified": "2026-07-23T23:16:24Z",
		"mac": "ENC[AES256_GCM,data:DK36PUWCAbfMEmNdKxrbd1d5ng+yVlVo9RfVZLWWcl5r2ZiEqupWqrYmKB8wUvTqNJ5xvxuQ8iTkwMNLXTak8JirOZoxbn0uUuyc9AQBk3T4ljjT4KvemObKV4ttRvt+ciQu/zvIEOAmEkyeoM0VZGBqtNhZgtX8xkbyHBWFhi0=,iv:Di6wIkzweyGDvqQkPgd4TwCdC4UnZH9mBfrl8ujAxAE=,tag:i0kZ6VIjdAtohsXn6CT5sw==,type:str]",
		"version": "3.13.2"
	}
}
