{
	"data": "ENC[AES256_GCM,data:nAmjJiqDyolcUiXUa2ML0pg6rkfJijd7kVJBgy2Egz7f8uTVZfQrjh84rWPO5vVVjgli9gQJlg1CvleI00Df93xxotytw8Xr+FxC0qVmqOSbfHY2l3yUqagnlm1kp+CuiwP46pFt7Ha8LVooHFHqcSuf+DT1xf1wch+kdiq5yNqcrQgSdbBFytt2a9AzTyhFbr4Bf07fZZS044jNdPGuwTdzBTnS4RASatp/DtyH/xdDxHRGHWgrCIlXfgo=,iv:uOlVY0msHizLkIHWrK0LRAY303r+C6/07Ejd53ibn/I=,tag:PaVw3qnpeLO5oJlg9/3/hQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MjBqTzZIMWZRSUxWZ1N0\nM1JuZGtiUHpuV2FmZzRiSm1JaEpSNWVTdnhFCkwvNmRzYWlTZ2JFQ0J2VVFGM1pW\nVUdCaWE4ak51ZVc5VURDOXIrU0RCOXMKLS0tIDJ6R25LaDRmNUdyL3dCb2RmYjBC\neXZrVFl0czZ1Wis1Q0tVNUdFS2czSlUK5cRZ/5MNQHwaA7UPy0+Krr0rizo3JMMh\n9v+FpaPY9D/30Lh4dlMUJavj+DJps01RM5u0nP5pRYQvWJnnt+g/eg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-12T11:40:09Z",
		"mac": "ENC[AES256_GCM,data:1lk8HpjSK9o67OieJoWXgU7y4lmlodnnnRG/EbOUMsj89RiZubDP6SRFkiJFPd+FmSPKp3ufBHrVEvLqxeNEJ2bfDZN84Tlj4Kz5rj7AatbNNJZcaDtLMoNG+U/7x+CC9aRysMR4P6RXZEJNxYuOy42mUrTECzToNMav9gWB5+Y=,iv:D5GsBq5L37/2tOItkUi9h1u9rYh2M0t+9VIKNAvhPwc=,tag:rn36g9L+7+lLbSw5Nqa2dQ==,type:str]",
		"version": "3.12.2"
	}
}
