{
	"data": "ENC[AES256_GCM,data:3KdOALfjHsD+kFo8/mu1BLMx3X5DrpaLZ39v77VMSVbwDtkkaP1Q+YVbPJZsBKW7Ckn0Wkt2rtfujAYy3hS/FagogY6dz5JShdlQq5aVS+1CsAqhma9mcDW3l9y6ZwYdt3QmXDAVaNBF7c6uqc8ZWTtzeLkEfqkrtQ8lvMOjbGy8o/oJl1RKsVojv3Mt8w2o7YQ+whRLAS6gbFFy57rgCv8odL4WWf2eKGgohAehUEZWYTc5TkJHm6pfj30=,iv:jpN1w0Nqu4gQXWBJsmm2QF5g3ZflATVXSQGL2weiaPE=,tag:D3QRbghCiLZjLB3/LOi0Dw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN2pmS2U2T2tlQWJQbU1K\nZlVoWklIVzFWZWxhRkNNZDhFRHJ3eUtkUzI0CjlUaWI5VEpJZ2RIb1BDbDZaUWRJ\nSkFPN3pwS2VJRmkwL0NYMjgwcktMYmcKLS0tIDRoWXg4VWZHOHZMN0NrdU95WUVk\nSTU2RjZKekxhV2g0YlZBV2xLUVduaXcKJUcClEHCTgHgRIGbat7IjgxisKnNOo4C\nVoqbbu5n6BPRigXBZqDkkFuYc6DSMCq0DttKkLXu92Wrg8l9aN2byA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c"
			}
		],
		"lastmodified": "2026-07-24T02:16:49Z",
		"mac": "ENC[AES256_GCM,data:VXTPD1vZWtCiVoIjKSlAPd+ijqDoWyE1f7/R0r7F0gQrWn4LGS5tzo42WinViaq1mQkSX1hBIM9uvnU6KRMwVbANd9X4Pyy8AoA1VWfoWABBBlQlsJvqpgTpqMefDwCQ7qphZVrvyOk0wRdw1NjygHmY3g4cAY7snVMCZ8bmFD0=,iv:nm6ZKDmQ6LuqNHsC0RgNfr2it6zYx7UaxJI1f1O5paE=,tag:2ea9VM35JylYHV/Aa/uzWw==,type:str]",
		"version": "3.13.2"
	}
}
