{
	"data": "ENC[AES256_GCM,data:gGJDKQNcA52FmP4PYTFv/AY6oHouBJgu08MIk1WNDY95EPfcrp9EzuSVtwSbs+kWHyfzXg3Lf9MZewmwwrXJoJ6WnO6X6YSB7Ra3UODN/Vsn9i27EEHnbsgfh5bFJ5q01XlXyd6Dgm+ChNNpndGqbMaN0+LJ4PUIXEB5LzT6ui2PnYwNsv7Srf+t3HL+n5sSd6i2QyUHZLNS8gYq25Vk25jEStlW475PuLdnkVFEMLDs9q48aKgUz8fXtII=,iv:7dSzIETcAzyI4kZHLpw2r9lgxVX5BKVs3HUdMWl13zk=,tag:nDC1Q0zYiKP0w+Ywq4/8wA==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SWpGUDFiQlpzSHhxU0Qv\nQlN6Yy94blgxWjQyTm5VVm9SMktKN21nenpvCmdxakE0K0o1citoWm5iQzQ1Y3lq\nREtzWXN1eXI5V21kOWtpcDh6dlYzdm8KLS0tIFlDZ0kzNmRqcXplb2ZOYVQ3TitI\nY3VzbmF5dGR0ODVYTTFJWW5mdXFYWVUK7s5uZqgsZIx1np4DHynY0ryoA4TyRh8p\nApzESqmWtGyDz9WgdfEeiD9jgmiKdPvJCU7bHPdOiqxKgesUlpU+Mw==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c"
			}
		],
		"lastmodified": "2026-06-12T04:59:36Z",
		"mac": "ENC[AES256_GCM,data:YsEUVlqVdq/Bsb7VlRsOjnKnXIRK7ebeGs5ofVcd1HtJpyzapbx4vhk0aMnKhH4NH07LrgFoJRtbeCCG8TtCaPV9t1JL0hP/G1pzAtvDBn9PkTDZjGgWKNku53Q60VQ8ArZzghjP+nShmikIDFJY4nxpaXyyy540m2dNsA/RAS4=,iv:nMWV5g0uCD5pFGyZ03ZcsD6MoSIW0O8xmTdPU/cP9yw=,tag:fOYO2tQ4+ECNE54LNJPH4g==,type:str]",
		"version": "3.13.1"
	}
}
